# Copyright (c) 2018-2023 MobileCoin Inc.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-pg-exporter.fullname" . }}
  labels:
    {{- include "prometheus-pg-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-pg-exporter.selectorLabels" . | nindent 4 }}
