FROM ubuntu:jammy

RUN  addgroup --system --gid 1000 app \
  && adduser --system --ingroup app --uid 1000 app

RUN  apt-get update \
  && apt-get upgrade -y \
  && rm -rf /var/lib/apt/lists/*

COPY prometheus-pg-exporter /usr/local/bin

USER app

CMD ["/usr/local/bin/prometheus-pg-exporter"]
