# Copyright (c) 2022-2023 MobileCoin Inc.
name: build-and-publish

on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: prometheus-pg-exporter
  DOCKER_ORG: mobilecoin
  CHART_REPO: https://harbor.mobilecoin.com/chartrepo/mobilecoinofficial-public

jobs:
  build:
    runs-on: [self-hosted, Linux, small]
    container: golang:1.20
    steps:
    - name: install zstd for gh cache bug
      run: |
        apt-get update -y
        apt-get install -y zstd

    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Cache
      id: cache
      uses: mobilecoinofficial/gh-actions/cache-go-binaries@708d32588d8bc83884ae65c557761b90d676c7fe
      with:
        cache_buster: ${{ vars.CACHE_BUSTER }}

    - name: Build
      if: "! steps.cache.outputs.cache-hit"
      run: |
        go mod vendor
        go build -v

    - name: Copy binaries to cache
      if: "! steps.cache.outputs.cache-hit"
      run: |
        mkdir -p cache/
        cp prometheus-pg-exporter cache/

  publish:
    runs-on: [self-hosted, Linux, small]
    needs:
    - build
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Cache
      uses: mobilecoinofficial/gh-actions/cache-go-binaries@708d32588d8bc83884ae65c557761b90d676c7fe
      with:
        cache_buster: ${{ vars.CACHE_BUSTER }}

    - name: Copy binaries from cache
      run: |
        cp cache/prometheus-pg-exporter ./

    - name: Docker
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: .internal-ci/docker/Dockerfile.${{ env.REPO }}
        flavor: latest=true
        images: ${{ env.DOCKER_ORG }}/${{ env.REPO }}
        tags: |
          type=ref,event=branch
          type=semver,pattern=v{{version}}
          type=sha
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish helm chart
      uses: mobilecoinofficial/gha-k8s-toolbox@v1
      with:
        action: helm-publish
        chart_app_version: ${{ github.ref_name }}
        chart_path: .internal-ci/helm/${{ env.REPO }}
        chart_repo: ${{ env.CHART_REPO }}
        chart_repo_password: ${{ secrets.HARBOR_PASSWORD }}
        chart_repo_username: ${{ secrets.HARBOR_USERNAME }}
        chart_version: ${{ github.ref_name }}

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true


00833a7ac6007349c26ca56e0a8d46732766fea8a167b2aa47213b2e3b264e8d-Linux-3918c051838aa92954135c733edf42710382535df37038ff39202ee0e239102b-go-build-artifacts

00833a7ac6007349c26ca56e0a8d46732766fea8a167b2aa47213b2e3b264e8d-Linux-3918c051838aa92954135c733edf42710382535df37038ff39202ee0e239102b-go-build-artifacts
